/**
 * Document Generation Templates
 * 
 * These templates define the structure and content for AI-generated documents.
 * Each document type has a specific format optimized for the insurance supplement workflow.
 */

export type DocumentType = 
  | 'delta_analysis'
  | 'cover_letter'
  | 'defense_notes'
  | 'supplement_letter'
  | 'rebuttal'
  | 'project_brief'
  | 'inspection_checklist'
  | 'photo_report'

export interface DocumentTemplate {
  type: DocumentType
  title: string
  description: string
  sections: string[]
  example?: string
}

export const DOCUMENT_TEMPLATES: Record<DocumentType, DocumentTemplate> = {
  delta_analysis: {
    type: 'delta_analysis',
    title: 'Delta Analysis Report',
    description: 'Comparison of carrier scope vs. code requirements and site conditions. Identifies missing, underscoped, and incorrect items.',
    sections: [
      'Summary',
      'Missing Items (Critical)',
      'Missing Items (High Priority)',
      'Quantity Corrections',
      'Code Compliance Issues',
      'Recommended Additions',
      'Total Estimated Impact',
      'Evidence Summary'
    ],
    example: `# Delta Analysis Report
**Property:** [Address]
**Claim #:** [Number]
**Carrier:** [Name]
**Date:** [Date]

## Summary
This analysis compares the carrier's scope against IRC code requirements, manufacturer installation instructions, and documented site conditions. We identified **[X] critical items** and **[X] additional items** that are missing or underscoped.

**Estimated Supplement Value:** $[X,XXX] - $[X,XXX]

## Missing Items - Critical (Code Required)

| Item | Code | Xactimate | Qty | Unit | Est. Value | Evidence |
|------|------|-----------|-----|------|------------|----------|
| Drip Edge | R905.2.8.5 | RFGDRIP | [X] | LF | $[X] | Photo p.[X] |
| Starter Course | R905.2.8.1 | RFGASTR | [X] | LF | $[X] | Measurement |
...

## Defense Notes
Each item includes a code-compliant defense note ready for Xactimate entry.

---
*Generated by QuickClaims AI*`
  },

  cover_letter: {
    type: 'cover_letter',
    title: 'Carrier Submission Cover Letter',
    description: 'Professional cover email/letter for supplement submission to insurance carrier.',
    sections: [
      'Subject Line',
      'Greeting',
      'Purpose Statement',
      'Key Deltas Summary',
      'Attachments List',
      'Requested Action',
      'Contact Information'
    ],
    example: `**Subject:** Supplement for Claim #[CLAIM NUMBER] — [PROPERTY ADDRESS]

Hello [Adjuster Name],

Please find attached the supplement package for the above-referenced claim. We have identified several items that require correction to ensure code compliance and restore the property to pre-loss condition.

**Key Corrections:**
• Drip edge missing — Required per IRC R905.2.8.5 at all eaves and rakes ([X] LF)
• Starter course omitted — Required per IRC R905.2.8.1 ([X] LF)
• Ice & water shield in valleys — Required per IRC R905.2.7.1 ([X] SF)
• Step flashing at sidewalls — Required per IRC R905.2.8.3 ([X] LF)
• Hip/ridge cap — Not included in waste per EagleView report ([X] LF)

**Attachments:**
1. Corrected Xactimate estimate with line-item defense notes
2. Photo packet organized by elevation and area
3. EagleView measurement report
4. IRC code reference pages

**Requested Action:**
Please review and confirm acceptance, or advise of any additional documentation needed. I will follow up within 48 hours.

Thank you for your attention to this matter.

Best regards,
[Name]
[Company]
[Phone] | [Email]`
  },

  defense_notes: {
    type: 'defense_notes',
    title: 'Line Item Defense Notes',
    description: 'Individual defense notes for each supplement line item with code/manufacturer citations.',
    sections: [
      'Item Description',
      'Code Reference',
      'Justification',
      'Photo Evidence Reference',
      'Quantity Basis'
    ],
    example: `## Defense Notes for Claim #[NUMBER]

### RFGDRIP - Drip Edge ([X] LF)
Drip edge is REQUIRED per IRC R905.2.8.5 at ALL eaves and rake edges of shingle roofs. The code states: "A drip edge shall be provided at eaves and rake edges of shingle roofs. Adjacent segments of drip edge shall be overlapped a minimum of 2 inches." This is a CODE REQUIREMENT, not optional. Measurement report confirms total eave ([X] LF) + rake ([X] LF) linear footage.

### RFGASTR - Starter Course ([X] LF)
Starter strip shingles REQUIRED per IRC R905.2.8.1 at ALL roof eaves: "Starter strip shingles, or the equivalent, shall be applied at all roof eaves." EagleView measurement report confirms this is NOT included in shingle waste calculation and must be added as a separate line item.

### RFGIWS - Ice & Water Shield ([X] SF)
Ice & water shield membrane required per IRC R905.2.7.1 and [Manufacturer] installation instructions. This area has documented history of ice dams. IWS must extend from eaves to a point at least 24" inside exterior wall line. Valley application requires ≥36" IWS per manufacturer specs. Total: [X] valleys × [X] LF × 3 ft width = [X] SF.

---
*Each note is ready to copy directly into Xactimate line item notes field.*`
  },

  supplement_letter: {
    type: 'supplement_letter',
    title: 'Full Supplement Letter',
    description: 'Comprehensive supplement letter with all deltas, defense notes, and supporting documentation references.',
    sections: [
      'Header Information',
      'Executive Summary',
      'Scope Comparison',
      'Missing Items Detail',
      'Code Citations',
      'Photo Evidence Index',
      'Cost Summary',
      'Conclusion'
    ],
    example: `# SUPPLEMENT REQUEST

**Re:** Claim #[NUMBER]
**Insured:** [Name]
**Property:** [Address]
**Date of Loss:** [Date]
**Carrier:** [Name]
**Adjuster:** [Name]

---

## Executive Summary

We have completed a comprehensive review of the carrier's estimate dated [date] against IRC code requirements, manufacturer installation instructions, and documented site conditions. This review identified **[X] items totaling an estimated $[X,XXX]** that are either missing from the original scope or require quantity corrections.

All supplement items are supported by:
- IRC building code requirements
- Manufacturer installation instructions
- Photographic evidence
- Measurement verification

---

## Items Summary Table

| # | Item | Code | Xactimate | Qty | Unit | Est. RCV |
|---|------|------|-----------|-----|------|----------|
| 1 | Drip Edge | R905.2.8.5 | RFGDRIP | [X] | LF | $[X] |
| 2 | Starter | R905.2.8.1 | RFGASTR | [X] | LF | $[X] |
...

**Total Supplement Request:** $[X,XXX]

---

[Detailed sections for each item follow...]`
  },

  rebuttal: {
    type: 'rebuttal',
    title: 'Rebuttal Response',
    description: 'Professional response to carrier objection with evidence-based counter-arguments.',
    sections: [
      'Objection Quoted',
      'Response',
      'Code/Manufacturer Citation',
      'Photo Evidence Reference'
    ],
    example: `## Rebuttal to Carrier Objection

**Claim #:** [NUMBER]
**Date:** [Date]
**Re:** [Item in question]

---

**Carrier Objection:**
> "[Quote the carrier's exact objection here]"

**Response:**

Our submission follows IRC [CODE] and [Manufacturer] installation instructions which specifically require [item] in this application. 

[Detailed response with specific code citation]

Photos on page [X] of our submission clearly show [specific evidence]. The measurement report confirms [specific measurement].

Per IRC [CODE]: "[exact code quote]"

We respectfully request this item be approved as submitted. Please advise if additional documentation is needed.

---

*Tone: Professional, courteous, evidence-first. No policy interpretation - construction, code, and manufacturer specs only.*`
  },

  project_brief: {
    type: 'project_brief',
    title: 'Project Brief',
    description: 'High-level project summary with scope, timeline, and key milestones.',
    sections: [
      'Project Overview',
      'Property Information',
      'Scope of Work',
      'Key Dates',
      'Status',
      'Next Steps'
    ],
    example: `# Project Brief

## [Client Name] - [Address]

### Overview
- **Project Type:** [Storm Damage / Hail Damage / Insurance Claim]
- **Date Created:** [Date]
- **Carrier:** [Name]
- **Claim #:** [Number]
- **Status:** [Current Status]

### Property Details
- **Address:** [Full Address]
- **Roof Type:** [Comp Shingle / Metal / Tile]
- **Squares:** [X]
- **Stories:** [X]
- **Pitch:** [X]/12

### Scope Summary
- Full roof replacement
- [X] squares of [shingle type]
- [Key line items]

### Timeline
| Milestone | Target Date | Status |
|-----------|-------------|--------|
| Intake Complete | [Date] | ✓ |
| Supplement Submitted | [Date] | ⏳ |
| SOL Expected | [Date] | - |
| Build Scheduled | TBD | - |

### Next Steps
1. [Next action item]
2. [Follow-up date]
3. [Required documents]`
  },

  inspection_checklist: {
    type: 'inspection_checklist',
    title: 'Inspection Checklist',
    description: 'Comprehensive checklist of required photos and documentation for field inspections.',
    sections: [
      'Claim Information',
      'Ground Level Photos',
      'Edge of Roof',
      'Roof Top',
      'Main Components',
      'Vents',
      'Additional Items',
      'Attic Check',
      'Additional Trades'
    ],
    example: `# Inspection Checklist
**Project:** [Address]
**Date:** [Date]

## Required Photos

### Ground Level (4 elevations)
- [ ] Front elevation
- [ ] Rear elevation
- [ ] Left side
- [ ] Right side

### Edge of Roof
- [ ] Starter course
- [ ] Underlayment visible
- [ ] Drip edge (note if painted)
- [ ] Shingle thickness with gauge
- [ ] Pitch measurement

### Roof Top
- [ ] All corners looking in
- [ ] All peaks looking out
- [ ] Overall condition

### Main Components
- [ ] Valley metal / Ice & water shield
- [ ] Hip and ridge lines
- [ ] Step flashing
- [ ] L/Wall flashing
- [ ] Chimney with measurement
- [ ] Chase cover

### Ventilation
- [ ] Pipe jacks / boots (qty: ___)
- [ ] Split boots (qty: ___)
- [ ] Box/turtle vents (qty: ___)
- [ ] Turbine vents (qty: ___)
- [ ] Ridge vent (LF: ___)
- [ ] Power vents (qty: ___)
- [ ] Exhaust caps (qty: ___)

### Attic (if accessible)
- [ ] Decking type: ___
- [ ] Rafter spacing: ___"
- [ ] Decking thickness: ___"
- [ ] Water damage visible?

**Total items: 50+ checkpoint items**`
  },

  photo_report: {
    type: 'photo_report',
    title: 'Photo Evidence Report',
    description: 'Organized photo documentation mapped to line items and code requirements.',
    sections: [
      'Photo Index',
      'By Elevation',
      'By Component',
      'Damage Documentation',
      'Measurement Evidence'
    ],
    example: `# Photo Evidence Report
**Claim #:** [NUMBER]
**Property:** [Address]

## Photo Index

### Elevation Photos
| # | Description | Elevation | Line Items Supported |
|---|-------------|-----------|---------------------|
| 1 | Front overview | North | RFGHIGH+ |
| 2 | Rear overview | South | RFGHIGH+ |

### Component Photos
| # | Description | Component | Code Reference |
|---|-------------|-----------|----------------|
| 5 | Valley at front/main | Valley metal | R905.2.8.2 |
| 6 | Step flashing at chimney | Step flashing | R905.2.8.3 |

### Damage Photos
| # | Description | Damage Type | Severity |
|---|-------------|-------------|----------|
| 10 | Hail impact on ridge | Hail | Moderate |

---
*Photos organized to support each supplement line item with code references.*`
  }
}

/**
 * Get template by document type
 */
export function getDocumentTemplate(type: DocumentType): DocumentTemplate {
  return DOCUMENT_TEMPLATES[type]
}

/**
 * Get all document types
 */
export function getDocumentTypes(): DocumentType[] {
  return Object.keys(DOCUMENT_TEMPLATES) as DocumentType[]
}

/**
 * Get document description
 */
export function getDocumentDescription(type: DocumentType): string {
  return DOCUMENT_TEMPLATES[type].description
}
