/**
 * Gamma API Integration for Document Generation
 * 
 * Gamma (gamma.app) is used for generating beautiful presentations and documents.
 * This module provides integration for creating professional:
 * - Supplement presentations
 * - Project briefs
 * - Estimate summaries
 */

const GAMMA_API_URL = 'https://api.gamma.app/v1'

interface GammaDocument {
  id: string
  title: string
  url: string
  thumbnailUrl?: string
  status: 'pending' | 'processing' | 'completed' | 'failed'
}

interface GenerateOptions {
  title: string
  content: string
  template?: 'professional' | 'modern' | 'minimal'
  theme?: 'light' | 'dark' | 'auto'
}

/**
 * Generate a document using Gamma AI
 */
export async function generateGammaDocument(options: GenerateOptions): Promise<GammaDocument | null> {
  const apiKey = process.env.GAMMA_API_KEY
  
  if (!apiKey) {
    // GAMMA_API_KEY not configured
    return null
  }

  try {
    const response = await fetch(`${GAMMA_API_URL}/generate`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        title: options.title,
        content: options.content,
        template: options.template || 'professional',
        theme: options.theme || 'light',
      }),
    })

    if (!response.ok) {
      // Gamma API returned an error
      return null
    }

    return await response.json()
  } catch {
    // Gamma API request failed
    return null
  }
}

/**
 * Generate a supplement presentation
 */
export async function generateSupplementPresentation(params: {
  insuredName: string
  propertyAddress: string
  claimNumber?: string
  carrierName: string
  items: Array<{
    description: string
    xactimateCode?: string
    rcv?: number
    defenseNote?: string
  }>
  totalAmount: number
  originalRCV: number
}): Promise<GammaDocument | null> {
  const { insuredName, propertyAddress, claimNumber, carrierName, items, totalAmount, originalRCV } = params

  const content = `
# Supplement Request

## Claim Information
- **Insured:** ${insuredName}
- **Property:** ${propertyAddress}
${claimNumber ? `- **Claim #:** ${claimNumber}` : ''}
- **Carrier:** ${carrierName}

## Summary
- **Original RCV:** $${originalRCV.toLocaleString()}
- **Supplement Amount:** $${totalAmount.toLocaleString()}
- **New Total:** $${(originalRCV + totalAmount).toLocaleString()}

## Supplement Items

${items.map((item, i) => `
### ${i + 1}. ${item.description}
${item.xactimateCode ? `**Code:** ${item.xactimateCode}` : ''}
${item.rcv ? `**RCV:** $${item.rcv.toFixed(2)}` : ''}
${item.defenseNote ? `\n${item.defenseNote}` : ''}
`).join('\n')}

## Contact
For questions regarding this supplement request, please contact the contractor.
`

  return generateGammaDocument({
    title: `Supplement Request - ${insuredName}`,
    content,
    template: 'professional',
  })
}

/**
 * Generate a project brief presentation
 */
export async function generateProjectBrief(params: {
  clientName: string
  address: string
  projectType: string
  overview?: string
  phases?: Array<{ name: string; tasks: string[]; durationDays: number }>
  materials?: Array<{ name: string; quantity: number; unit: string }>
  totalCost?: number
}): Promise<GammaDocument | null> {
  const { clientName, address, projectType, overview, phases, materials, totalCost } = params

  const content = `
# ${projectType} Project Brief
## ${clientName}

### Property
${address}

${overview ? `### Overview\n${overview}` : ''}

${phases && phases.length > 0 ? `
### Project Timeline

${phases.map((phase, i) => `
#### Phase ${i + 1}: ${phase.name}
**Duration:** ${phase.durationDays} days

${phase.tasks.map(task => `- ${task}`).join('\n')}
`).join('\n')}
` : ''}

${materials && materials.length > 0 ? `
### Materials Required

| Material | Quantity | Unit |
|----------|----------|------|
${materials.map(m => `| ${m.name} | ${m.quantity} | ${m.unit} |`).join('\n')}
` : ''}

${totalCost ? `
### Estimated Cost
**Total:** $${totalCost.toLocaleString()}
` : ''}

---
*Generated by QuickClaims AI*
`

  return generateGammaDocument({
    title: `${projectType} - ${clientName}`,
    content,
    template: 'modern',
  })
}

/**
 * Check if Gamma is configured
 */
export function isGammaConfigured(): boolean {
  return !!process.env.GAMMA_API_KEY
}
